version: '3.8'
services:
 
  hangfire:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"

  worker1:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire

  worker2:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire

  worker3:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire

  worker4:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire

  worker5:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire
